// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqnwecbjgvcomvhtxgdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xbndlY2JqZ3Zjb212aHR4Z2RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDk4MTMsImV4cCI6MjA2OTI4NTgxM30.__ivDWvPB97sKXXIz7jw-zeAeJLKF5IzH9Xme30207k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});